### ISSUE TITLE
Publish specific version of FreeCAD

### ISSUE THREAD

**Issue by lutangar** [webknjaz/docker-freecad-cli#1]
Hey there, I'm wondering if you're planning to maintain and publish specific version of FreeCAD on Docker Hub.
I'll be interesting in 0.17 for instance.

You could use docker arguments in such way it maintain the current behavior:
```
ARG FREECAD_VERSION="master"
ENV FREECAD_VERSION=$FREECAD_REPO
```
And then:
```
docker build --build-arg FREECAD_VERSION=releases/FreeCAD-0-17
```

Also you may consider adding an entry-point in your Dockerfile. Maybe something like this would be enough:
```
ENTRYPOINT ["FreeCAD"]
```

Cheers.

**Comment by webknjaz** [comment]
Hi @lutangar,

I'm open to suggestions and PRs. This repo has been created as a part of my work for a client who uses it in their CAD automation without Qt dependencies (with no GUI flag). I tend to fix this time to time when needed. However, this doesn't get my full attention.

That said, PRs are welcome. If you're not up to it I might be implementing your suggestions at some point if I have the time or if my client will need some fixes/improvements. But no promises.

If you have a real need in this project being up-to-date, I can suggest you become a co-maintainer.

**Comment by lutangar** [comment]
Hey thanks for the proposal, but I went with this simple Dockerfile instead:
```
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository --enable-source ppa:freecad-maintainers/freecad-stable
RUN apt-get update

# Install the dependencies needed to build FreeCAD
RUN apt-get build-dep -y freecad

# Install the dependencies needed to run FreeCAD (and a build of FreeCAD itself)
RUN apt-get install -y freecad

ENTRYPOINT ["freecadcmd"]
```
Keep up the good work!

**Comment by webknjaz** [comment]
Yeah... Back when I was putting it all together there were complications with running FreeCAD under Python 3.

**Comment by webknjaz** [comment]
FWIW `latest` now has `FreeCAD 0.18, Libs: 0.18R14993 (Git)` w/ `Python 3.7.0 (default, Aug  6 2018, 20:07:46)`:
```
...
Status: Downloaded newer image for webknjaz/freecad-cli:latest
root@312e8d2a1f23:/# python3.7
Python 3.7.0 (default, Aug  6 2018, 20:07:46) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import FreeCAD
FreeCAD 0.18, Libs: 0.18R14993 (Git)
>>> FreeCAD
<module 'FreeCAD' from '/usr/local/lib/FreeCAD.so'>
```
